
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe0x\xa5\x93<\n\x15\xc2\xae\xe3]\xe0\t\x85\x8ay'
    
_lr_action_items = {'COMMENT':([0,],[1,]),'HEXI':([0,2,3,8,10,11,],[2,-13,-12,2,-11,2,]),'DECI':([0,2,3,8,10,11,],[3,-13,-12,3,-11,3,]),'DIRECTIVE':([0,],[4,]),'OFFSET':([0,2,3,8,10,11,],[10,-13,-12,10,-11,10,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[-6,-2,-13,-12,-4,-3,-1,0,-9,-5,-11,-8,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[9,]),'instruction':([0,],[5,]),'list':([0,],[6,]),'system':([0,],[7,]),'argument':([0,8,11,],[8,11,12,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> system","S'",1,None,None,None),
  ('system -> list','system',1,'p_system','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',9),
  ('list -> COMMENT','list',1,'p_comment','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',15),
  ('list -> instruction','list',1,'p_instruction','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',21),
  ('instruction -> DIRECTIVE','instruction',1,'p_directive','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',27),
  ('instruction -> command','instruction',1,'p_instr_command','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',33),
  ('command -> <empty>','command',0,'p_command','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',39),
  ('command -> argument argument argument','command',3,'p_command','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',40),
  ('command -> argument argument','command',2,'p_command','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',41),
  ('command -> argument','command',1,'p_command','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',42),
  ('argument -> <empty>','argument',0,'p_argument','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',48),
  ('argument -> OFFSET','argument',1,'p_argument','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',49),
  ('argument -> DECI','argument',1,'p_argument','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',50),
  ('argument -> HEXI','argument',1,'p_argument','/home/alexandra/Desktop/cb-project/code/parse_yacc.py',51),
]
